### ISSUE TITLE
Consider making TemporaryDirectory public?

### ISSUE THREAD

**Issue by alexito4** [mxcl/Path.swift#23]
Hi, 

I was checking out swiftsh code and found `Path.mktemp` which is really useful, but when trying to use it I was surprised is not available in `Path`. I see that in this library is just used as an helper for the tests but swiftsh uses it for production code in `eject`. 

Would you consider making `TemporaryDirectory` part of the Path API? Or is there any reason why that's a bad idea?

Cheers

**Comment by mxcl** [comment]
Hi, `TemporaryDirectory` was public, but I removed it: cd30e8.

I did this because I didn't consider it within the responsibility boundary of this library. An entire library could be dedicated to temporary directories (and files) and thus would have better API and a more thorough implementation.

A good example of a better implementation is SwiftPM’s Utility library. Not that I think anyone should use that, but it's better for this particular area.

Thanks.

**Comment by alexito4** [comment]
That makes sense thanks 👍 

For SwiftPM, you refer to this file? [TemporaryFile.swift](https://github.com/apple/swift-package-manager/blob/adcd5544e9e7d7d4e59c078eb42ff0de4350a0c4/Sources/Basic/TemporaryFile.swift)

we can close this then 😉 

Cheers

**Comment by mxcl** [comment]
Yeah that one. You can import it if you depend on the whole of SwiftPM, but that's why I say I wouldn't recommend it since it imports a lot of other stuff, and Apple themselves say you shouldn't depend on libUtility.

Thanks for the report, I consider this an area I may in future make a separate library for, in the mean time feel free to vendor the file!
