### ISSUE TITLE
Path conflicts with SwiftUI.Path, no way to disambiguate

### ISSUE THREAD

**Issue by JetForMe** [mxcl/Path.swift#89]
Alas, if you import both `Path` and `SwiftUI`, you'll get a compiler error when using `Path` in your code, and there’s no way to disambiguate `Path.Path`. In a SwiftPM project, you can alias the module name when you import it, but there appears to be  no way to do that in Xcode.

**Comment by JetForMe** [comment]
Ah, it seems you already `typealias PathStruct = Path`. That may be all I need. Will report back shortly.

**Comment by JetForMe** [comment]
Yes, that solved my issue.

**Comment by mxcl** [comment]
I should document this for sure.

**Comment by JetForMe** [comment]
I did this as a solution myself, called it `SwiftPath`, after struggling for 20 minutes to come up with a more precise name. An alternative would be to change the name of the package (`PathUtil`?), but I had a hard time there, too.

I suppose `FilePath` would work.

**Comment by mxcl** [comment]
Changing the name of the package would be a breaking change requiring a major bump. Can do, but it's a big deal.

Really the issue is in the lack of namespacing in Swift for packages. It’s ironic since in ObjC Apple recommended you namespace with a three letter prefix (they said two letter prefixes were reserved for themselves). Then with Swift they said: you don’t need to namespace anymore!

But turns out there are these situations where you have to.

**Comment by JetForMe** [comment]
Indeed. Swift could have done what Java does with namespacing. It’s incredibly powerful and allows for fine-grained access control, and is opt-in, but alas. It’s not the only shortcoming. I think the typealias is the best compromise, I just wasn't happy with either of our name selections (they're both so generic lol).
